# Development override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  thread-dump-rest:
    build:
      context: .
      dockerfile: Dockerfile
      target: build  # Use build stage for development
    volumes:
      # Mount source code for hot-reloading (if using spring-boot-devtools)
      - ./src:/app/src:ro
      - ./target:/app/target:rw
    environment:
      - SPRING_PROFILES_ACTIVE=docker,dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - JAVA_OPTS=-Xmx256m -Xms128m -Dspring.devtools.restart.enabled=true
    ports:
      - "8080:8080"
      - "35729:35729"  # LiveReload port

  thread-dump-mcp:
    build:
      context: .
      dockerfile: Dockerfile  
      target: build
    volumes:
      - ./src:/app/src:ro
      - ./target:/app/target:rw
    environment:
      - SPRING_PROFILES_ACTIVE=mcp,docker,dev
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - JAVA_OPTS=-Xmx128m -Xms64m -Dspring.devtools.restart.enabled=true
    ports:
      - "8081:8081" 
      - "8082:8082"