# MCP-focused configuration profile
server:
  port: 8081
  servlet:
    context-path: /mcp

spring:
  application:
    name: thread-dump-diagnostic-agent-mcp
    
logging:
  level:
    com.tinusj.threaddump.skill: DEBUG
    com.tinusj.threaddump.controller: INFO
    com.tinusj.threaddump: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [MCP] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  server:
    port: 8082
    base-path: /actuator

# MCP-optimized settings
thread-dump:
  analysis:
    max-threads-warning: 1500
    deadlock-detection: true
    blocked-threads-threshold: 15
    waiting-threads-threshold: 75
  reports:
    default-format: JSON  # MCP prefers JSON format
    include-thread-details: true
    include-stack-traces: true