server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: thread-dump-diagnostic-agent
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  # MCP server configuration will be enabled when Spring AI MCP Server is available
  # ai:
  #   mcp:
  #     server:
  #       enabled: true
  #       name: thread-dump-analyzer
  #       description: "MCP Server for analyzing Java thread dumps"
  #       version: "1.0.0"

logging:
  level:
    com.tinusj.threaddump: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

thread-dump:
  analysis:
    max-threads-warning: 1000
    deadlock-detection: true
    blocked-threads-threshold: 10
    waiting-threads-threshold: 50
  reports:
    default-format: JSON
    include-thread-details: true
    include-stack-traces: true